"""Public contract for the ingestion capability.

Ingestion normalizes source-specific robotic data (ROS 1 bags, ROS 2 bags,
recorded datasets) into canonical, backend-agnostic sensor observations, and
persists them as a reusable, immutable sequence artifact. See
``src/contextmap/ingestion/docs/README.md`` for the full capability
documentation.
"""

from contextmap.ingestion.calibration import (
    CalibrationEntry,
    CalibrationError,
    CalibrationProvenance,
    CalibrationSet,
    CameraModel,
    DistortionModel,
    FisheyeCameraModel,
    PinholeCameraModel,
    RigidTransform,
    camera_model_kind,
    validate_calibration_set,
)
from contextmap.ingestion.diagnostics import (
    FrameGraphDiagnostics,
    ModalitySummary,
    SequenceDiagnostics,
    SequenceSummary,
    summarize_observations,
)
from contextmap.ingestion.models import (
    MODALITY_NAMES,
    CalibrationReferenceId,
    Covariance3x3,
    Covariance6x6,
    ExternalPoseMeasurement,
    FrameId,
    ImageEncoding,
    ImageObservation,
    ImuObservation,
    LidarObservation,
    PointFieldDataType,
    PointFieldDescriptor,
    SensorId,
    SourceObservation,
    SourceObservationId,
    SourceProvenance,
    observation_modality,
)
from contextmap.ingestion.sequence_artifact import (
    IncompleteSequenceArtifactError,
    SequenceArtifactError,
    SequenceArtifactFileEntry,
    SequenceArtifactId,
    SequenceArtifactManifest,
    SequenceArtifactReader,
    SequenceArtifactWriter,
)
from contextmap.ingestion.sequence_provenance import (
    SequenceProvenance,
    compute_configuration_hash,
    compute_content_identity,
    compute_source_content_hash,
    current_code_version,
)
from contextmap.ingestion.sequence_selection import (
    ExplicitIdsSelection,
    FrameRangeSelection,
    FullSequenceSelection,
    SequenceSelection,
    SequenceSelectionError,
    SequenceSelectionResult,
    TimestampRangeSelection,
    decode_selection,
    encode_selection,
    resolve_selection,
    selection_identity,
)
from contextmap.ingestion.source_adapter import (
    MissingRequiredTopicError,
    SourceAdapter,
    SourceAdapterCapabilities,
    SourceAdapterConfig,
    SourceAdapterError,
    SourceAdapterWarning,
    SourceTopicMapping,
    UnsupportedSourceMessageError,
)
from contextmap.ingestion.synchronization import (
    DroppedEvent,
    ModalityAssociation,
    ProcessingObservation,
    SynchronizationConfig,
    SynchronizationDecision,
    SynchronizationDiagnostics,
    synchronize,
)
from contextmap.ingestion.validation import (
    validate_frame_references,
    validate_image_observation,
    validate_lidar_observation,
    validate_observations,
    validate_timestamp_ordering,
)

__all__ = [
    "MODALITY_NAMES",
    "CalibrationEntry",
    "CalibrationError",
    "CalibrationProvenance",
    "CalibrationReferenceId",
    "CalibrationSet",
    "CameraModel",
    "Covariance3x3",
    "Covariance6x6",
    "DistortionModel",
    "DroppedEvent",
    "ExplicitIdsSelection",
    "ExternalPoseMeasurement",
    "FisheyeCameraModel",
    "FrameGraphDiagnostics",
    "FrameId",
    "FrameRangeSelection",
    "FullSequenceSelection",
    "ImageEncoding",
    "ImageObservation",
    "ImuObservation",
    "IncompleteSequenceArtifactError",
    "LidarObservation",
    "MissingRequiredTopicError",
    "ModalityAssociation",
    "ModalitySummary",
    "PinholeCameraModel",
    "PointFieldDataType",
    "PointFieldDescriptor",
    "ProcessingObservation",
    "RigidTransform",
    "SensorId",
    "SequenceArtifactError",
    "SequenceArtifactFileEntry",
    "SequenceArtifactId",
    "SequenceArtifactManifest",
    "SequenceArtifactReader",
    "SequenceArtifactWriter",
    "SequenceDiagnostics",
    "SequenceProvenance",
    "SequenceSelection",
    "SequenceSelectionError",
    "SequenceSelectionResult",
    "SequenceSummary",
    "SourceAdapter",
    "SourceAdapterCapabilities",
    "SourceAdapterConfig",
    "SourceAdapterError",
    "SourceAdapterWarning",
    "SourceObservation",
    "SourceObservationId",
    "SourceProvenance",
    "SourceTopicMapping",
    "SynchronizationConfig",
    "SynchronizationDecision",
    "SynchronizationDiagnostics",
    "TimestampRangeSelection",
    "UnsupportedSourceMessageError",
    "camera_model_kind",
    "compute_configuration_hash",
    "compute_content_identity",
    "compute_source_content_hash",
    "current_code_version",
    "decode_selection",
    "encode_selection",
    "observation_modality",
    "resolve_selection",
    "selection_identity",
    "summarize_observations",
    "synchronize",
    "validate_calibration_set",
    "validate_frame_references",
    "validate_image_observation",
    "validate_lidar_observation",
    "validate_observations",
    "validate_timestamp_ordering",
]
