"""Public contract for the semantic fusion capability.

Semantic Fusion accumulates evidence from several views over a shared spatial
support and keeps it as :class:`FusedEvidence`: the competing hypotheses, the
exact claims and typed signals behind each, the conflicts between physical
observations and what is simply unknown. It creates no entity identity, elects
no winner and never merges heterogeneous scores into one number. See
``src/contextmap/semantic_fusion/docs/README.md`` for the full capability
documentation.
"""

from contextmap.semantic_fusion.accumulation import (
    BASELINE_ACCUMULATION_POLICY_ID,
    BaselineAccumulationPolicy,
    accumulate_baseline_evidence,
    label_key,
)
from contextmap.semantic_fusion.grouping import (
    PHYSICAL_OBSERVATION_GROUPING_POLICY_ID,
    PhysicalObservationGrouping,
    group_by_physical_observation,
)
from contextmap.semantic_fusion.models import (
    ChannelProvenance,
    ComponentFactor,
    ComponentTreatment,
    ContributionWeight,
    EvidenceChannel,
    EvidenceContribution,
    EvidenceContributionId,
    EvidenceReference,
    EvidenceStance,
    FusedEvidence,
    FusedEvidenceId,
    FusedEvidenceProvenance,
    FusedHypothesis,
    FusedHypothesisId,
    FusionSupport,
    FusionSupportId,
    FusionSupportProvenance,
    HypothesisEvidence,
    HypothesisSupport,
    ObservationFactor,
    ObservationQualityRef,
    PhysicalObservationGroup,
    PointRepresentationRef,
    QualityWeighting,
    ScoreReference,
    SupportSignal,
    SupportSignalKind,
    UncertaintyKind,
    UncertaintyRecord,
    evidence_contribution_id_for,
    fused_evidence_id_for,
)
from contextmap.semantic_fusion.quality_aware import (
    QUALITY_AWARE_ACCUMULATION_POLICY_ID,
    QualityAwareAccumulationPolicy,
    QualityInput,
    QualityRamp,
    accumulate_quality_aware_evidence,
)
from contextmap.semantic_fusion.run_artifact import (
    FusionOutcome,
    FusionRunArtifactError,
    FusionRunLineage,
    IncompleteFusionRunArtifactError,
    SemanticFusionDebugLevel,
    SemanticFusionRunId,
    SemanticFusionRunManifest,
    SemanticFusionRunReader,
    SemanticFusionRunWriter,
    allocate_fusion_run_index,
    rebuild_fusion_run_registry,
)
from contextmap.semantic_fusion.support import (
    GEOMETRY_OVERLAP_SUPPORT_POLICY_ID,
    ExcludedObservation,
    FusionSupportBuild,
    GeometryOverlapSupportPolicy,
    build_fusion_supports,
)

__all__ = [
    "BASELINE_ACCUMULATION_POLICY_ID",
    "GEOMETRY_OVERLAP_SUPPORT_POLICY_ID",
    "PHYSICAL_OBSERVATION_GROUPING_POLICY_ID",
    "QUALITY_AWARE_ACCUMULATION_POLICY_ID",
    "BaselineAccumulationPolicy",
    "ChannelProvenance",
    "ComponentFactor",
    "ComponentTreatment",
    "ContributionWeight",
    "EvidenceChannel",
    "EvidenceContribution",
    "EvidenceContributionId",
    "EvidenceReference",
    "EvidenceStance",
    "ExcludedObservation",
    "FusedEvidence",
    "FusedEvidenceId",
    "FusedEvidenceProvenance",
    "FusedHypothesis",
    "FusedHypothesisId",
    "FusionOutcome",
    "FusionRunArtifactError",
    "FusionRunLineage",
    "FusionSupport",
    "FusionSupportBuild",
    "FusionSupportId",
    "FusionSupportProvenance",
    "GeometryOverlapSupportPolicy",
    "HypothesisEvidence",
    "HypothesisSupport",
    "IncompleteFusionRunArtifactError",
    "ObservationFactor",
    "ObservationQualityRef",
    "PhysicalObservationGroup",
    "PhysicalObservationGrouping",
    "PointRepresentationRef",
    "QualityAwareAccumulationPolicy",
    "QualityInput",
    "QualityRamp",
    "QualityWeighting",
    "ScoreReference",
    "SemanticFusionDebugLevel",
    "SemanticFusionRunId",
    "SemanticFusionRunManifest",
    "SemanticFusionRunReader",
    "SemanticFusionRunWriter",
    "SupportSignal",
    "SupportSignalKind",
    "UncertaintyKind",
    "UncertaintyRecord",
    "accumulate_baseline_evidence",
    "accumulate_quality_aware_evidence",
    "allocate_fusion_run_index",
    "build_fusion_supports",
    "evidence_contribution_id_for",
    "fused_evidence_id_for",
    "group_by_physical_observation",
    "label_key",
    "rebuild_fusion_run_registry",
]
