"""Public contract for the semantic mapping capability.

Semantic Mapping materializes fused evidence as persistent semantic entities inside one
semantic-map artifact. An :class:`Entity` keeps the exact 3D support, every semantic hypothesis,
the evidence chain and the temporal state; it never decides whether two entities are the same
physical object, which belongs to Entity Resolution. See
``src/contextmap/semantic_mapping/docs/README.md`` for the full capability documentation.
"""

from contextmap.semantic_mapping.evidence import (
    EntityEvidenceLinks,
    EntityFeatureRef,
    FusedEvidenceRef,
    evidence_links_from_fused_evidence,
    feature_refs_of,
    fusion_artifact_digest,
)
from contextmap.semantic_mapping.evidence_integrity import (
    ContributionTrace,
    EntityEvidenceTrace,
    EvidenceIntegrityIssue,
    EvidenceIntegrityKind,
    EvidenceTraceError,
    FusedEvidenceSource,
    GeometrySourceTrace,
    trace_entity_evidence,
    trace_geometry_sources,
    validate_entity_evidence,
)
from contextmap.semantic_mapping.geometry import (
    GEOMETRY_SUMMARY_ALGORITHM_ID,
    EmptyGeometrySupportError,
    EntityGeometry,
    EntityOrientation,
    GeometryDiagnostic,
    GeometryDiagnosticKind,
    GeometryResolutionError,
    GeometrySummaryPolicy,
    OrientationPolicy,
    SpatialSummaryProvenance,
    SupportStatistics,
    geometry_set_digest,
    resolve_geometry,
    summarize_geometry,
    verify_geometry_summary,
)
from contextmap.semantic_mapping.models import (
    Entity,
    EntityId,
    EntityProvenance,
    EntityReference,
    EntitySet,
    ForeignEntityReferenceError,
    SemanticMapId,
    UnknownEntityError,
)
from contextmap.semantic_mapping.semantic_state import (
    AmbiguityState,
    AttributeOrigin,
    EntityAttribute,
    EntityHypothesis,
    EntityHypothesisRef,
    EntitySemanticState,
    EntityUncertainty,
    SemanticStateProvenance,
    derive_ambiguity_state,
)
from contextmap.semantic_mapping.state_mapping import (
    CLASS_ATTRIBUTE_DERIVATION_ID,
    PRIMARY_HYPOTHESIS_POLICY_ID,
    SEMANTIC_STATE_MAPPING_RULE_ID,
    semantic_state_from_fused_evidence,
)
from contextmap.semantic_mapping.temporal import (
    TEMPORAL_SUMMARY_RULE_ID,
    EntityLifecycle,
    EntityTemporalState,
    ObservationRef,
    TemporalEvidenceError,
    TemporalProvenance,
    summarize_temporal_state,
)

__all__ = [
    "CLASS_ATTRIBUTE_DERIVATION_ID",
    "GEOMETRY_SUMMARY_ALGORITHM_ID",
    "PRIMARY_HYPOTHESIS_POLICY_ID",
    "SEMANTIC_STATE_MAPPING_RULE_ID",
    "TEMPORAL_SUMMARY_RULE_ID",
    "AmbiguityState",
    "AttributeOrigin",
    "ContributionTrace",
    "EmptyGeometrySupportError",
    "Entity",
    "EntityAttribute",
    "EntityEvidenceLinks",
    "EntityEvidenceTrace",
    "EntityFeatureRef",
    "EntityGeometry",
    "EntityHypothesis",
    "EntityHypothesisRef",
    "EntityId",
    "EntityLifecycle",
    "EntityOrientation",
    "EntityProvenance",
    "EntityReference",
    "EntitySemanticState",
    "EntitySet",
    "EntityTemporalState",
    "EntityUncertainty",
    "EvidenceIntegrityIssue",
    "EvidenceIntegrityKind",
    "EvidenceTraceError",
    "ForeignEntityReferenceError",
    "FusedEvidenceRef",
    "FusedEvidenceSource",
    "GeometryDiagnostic",
    "GeometryDiagnosticKind",
    "GeometryResolutionError",
    "GeometrySourceTrace",
    "GeometrySummaryPolicy",
    "ObservationRef",
    "OrientationPolicy",
    "SemanticMapId",
    "SemanticStateProvenance",
    "SpatialSummaryProvenance",
    "SupportStatistics",
    "TemporalEvidenceError",
    "TemporalProvenance",
    "UnknownEntityError",
    "derive_ambiguity_state",
    "evidence_links_from_fused_evidence",
    "feature_refs_of",
    "fusion_artifact_digest",
    "geometry_set_digest",
    "resolve_geometry",
    "semantic_state_from_fused_evidence",
    "summarize_geometry",
    "summarize_temporal_state",
    "trace_entity_evidence",
    "trace_geometry_sources",
    "validate_entity_evidence",
    "verify_geometry_summary",
]
