"""Public contract for the entity resolution capability.

Entity Resolution decides, from typed and separately preserved evidence, whether semantic entities
describe the same physical object, distinct objects, or cannot be told apart, and materializes the
resolved entities that explicit decisions justify inside one immutable resolution artifact. It
never mutates a source entity and never turns a single score into an identity. See
``src/contextmap/entity_resolution/docs/README.md`` for the full capability documentation.
"""

from contextmap.entity_resolution.channels import (
    AppearanceEvidence,
    AppearanceMeasurement,
    AttributeComparison,
    ChannelEvidence,
    EvidenceStatus,
    FeatureContribution,
    Finding,
    GeometryEvidence,
    GeometryMeasurement,
    LabelComparison,
    LabelRelation,
    MatchChannel,
    PointRepresentationEvidence,
    RepresentationMeasurement,
    RepresentationRef,
    SemanticEvidence,
    SemanticMeasurement,
    SupportDistance,
    TemporalEvidence,
    TemporalMeasurement,
    Unavailability,
    UnavailableReason,
)
from contextmap.entity_resolution.decision import (
    DecisionProvenance,
    PolicyStage,
    ResolutionDecision,
    ResolutionDecisionId,
    ResolutionOutcome,
    TriggeredRule,
    UnresolvedReason,
    decision_id_for,
)
from contextmap.entity_resolution.evidence import (
    COMPARISON_GATES_POLICY_ID,
    ComparisonId,
    EntityMatchEvidence,
    GateResult,
    MatchEvidenceProvenance,
    comparison_id_for,
    evaluate_comparison_gates,
)
from contextmap.entity_resolution.geometry_comparison import (
    GEOMETRY_COMPARISON_POLICY_ID,
    GeometryComparisonPolicy,
    SupportDistancePolicy,
    compare_geometry,
)
from contextmap.entity_resolution.models import (
    EntityResolutionRunId,
    PolicyRef,
    ResolvedEntityId,
    ResolvedEntityReference,
    reference_order,
)
from contextmap.entity_resolution.retrieval import (
    CANDIDATE_RETRIEVAL_POLICY_ID,
    CandidacyAssessment,
    CandidateRetrievalPolicy,
    EntityCandidate,
    EntityCandidateSet,
    EntitySpatialIndex,
    ExclusionReason,
    RetrievalDiagnostics,
    RetrievalReason,
    candidate_pairs,
    explain_candidacy,
    retrieve_candidate_sets,
)
from contextmap.entity_resolution.semantic_comparison import (
    BASELINE_REFINEMENT_MODIFIERS,
    SEMANTIC_COMPATIBILITY_POLICY_ID,
    SemanticCompatibilityPolicy,
    compare_labels,
    compare_semantics,
    normalize_label,
)
from contextmap.entity_resolution.serialization import (
    decode_candidate_set,
    decode_match_evidence,
    decode_resolution_decision,
    decode_resolved_entity_reference,
    encode_candidate_set,
    encode_match_evidence,
    encode_resolution_decision,
    encode_resolved_entity_reference,
)
from contextmap.entity_resolution.temporal_comparison import (
    TEMPORAL_COMPATIBILITY_POLICY_ID,
    TemporalCompatibilityPolicy,
    compare_temporal,
)

__all__ = [
    "BASELINE_REFINEMENT_MODIFIERS",
    "CANDIDATE_RETRIEVAL_POLICY_ID",
    "COMPARISON_GATES_POLICY_ID",
    "GEOMETRY_COMPARISON_POLICY_ID",
    "SEMANTIC_COMPATIBILITY_POLICY_ID",
    "TEMPORAL_COMPATIBILITY_POLICY_ID",
    "AppearanceEvidence",
    "AppearanceMeasurement",
    "AttributeComparison",
    "CandidacyAssessment",
    "CandidateRetrievalPolicy",
    "ChannelEvidence",
    "ComparisonId",
    "DecisionProvenance",
    "EntityCandidate",
    "EntityCandidateSet",
    "EntityMatchEvidence",
    "EntityResolutionRunId",
    "EntitySpatialIndex",
    "EvidenceStatus",
    "ExclusionReason",
    "FeatureContribution",
    "Finding",
    "GateResult",
    "GeometryComparisonPolicy",
    "GeometryEvidence",
    "GeometryMeasurement",
    "LabelComparison",
    "LabelRelation",
    "MatchChannel",
    "MatchEvidenceProvenance",
    "PointRepresentationEvidence",
    "PolicyRef",
    "PolicyStage",
    "RepresentationMeasurement",
    "RepresentationRef",
    "ResolutionDecision",
    "ResolutionDecisionId",
    "ResolutionOutcome",
    "ResolvedEntityId",
    "ResolvedEntityReference",
    "RetrievalDiagnostics",
    "RetrievalReason",
    "SemanticCompatibilityPolicy",
    "SemanticEvidence",
    "SemanticMeasurement",
    "SupportDistance",
    "SupportDistancePolicy",
    "TemporalCompatibilityPolicy",
    "TemporalEvidence",
    "TemporalMeasurement",
    "TriggeredRule",
    "Unavailability",
    "UnavailableReason",
    "UnresolvedReason",
    "candidate_pairs",
    "compare_geometry",
    "compare_labels",
    "compare_semantics",
    "compare_temporal",
    "comparison_id_for",
    "decision_id_for",
    "decode_candidate_set",
    "decode_match_evidence",
    "decode_resolution_decision",
    "decode_resolved_entity_reference",
    "encode_candidate_set",
    "encode_match_evidence",
    "encode_resolution_decision",
    "encode_resolved_entity_reference",
    "evaluate_comparison_gates",
    "explain_candidacy",
    "normalize_label",
    "reference_order",
    "retrieve_candidate_sets",
]
