"""Public contract for the runtime capability.

The runtime resolves configuration, selects and constructs backends, and orchestrates
stages. It owns no scientific logic: segmentation, projection, fusion and every other
domain rule stay inside their capabilities. See ``docs/runtime-composition.md`` and
``src/contextmap/runtime/docs/README.md``.
"""

from contextmap.runtime.artifacts import ArtifactRef
from contextmap.runtime.catalog import (
    CANONICAL_PROFILE_ID,
    BackendSpec,
    ComponentSpec,
    Interception,
    RuntimePreset,
    StageDeclaration,
    StageInput,
)
from contextmap.runtime.composition import (
    ComposedRuntime,
    FeatureBuildScope,
    RuntimeProvider,
    compose,
)
from contextmap.runtime.config import (
    CONFIG_SCHEMA_VERSION,
    DEBUG_LEVELS,
    EFFECTIVE_CONFIG_FILENAME,
    ComponentConfig,
    ConfigProblem,
    ConfigurationError,
    ConfigurationSource,
    EffectiveConfig,
    InputsConfig,
    PipelineConfig,
    PoliciesConfig,
    ResolvedSecrets,
    ResourcesConfig,
    RuntimeConfig,
    check_availability,
    check_component_availability,
    check_selection,
    parse_override,
    read_effective_config,
    resolve_effective_config,
    resolve_secrets,
    write_effective_config,
)
from contextmap.runtime.errors import (
    BackendConfigurationError,
    BackendRuntimeMissingError,
    BackendUnavailableError,
    CompositionError,
    PipelineError,
    PlanDocumentError,
    PreflightError,
    ReuseError,
    StageExecutionError,
    StageUnavailableError,
)
from contextmap.runtime.pipeline import (
    ExecutionPlan,
    ExecutionRecord,
    PipelinePlan,
    PlannedInput,
    PlannedStage,
    PreflightReport,
    StageExecutor,
    StageRecord,
    StageRequest,
    predict_reuse,
    preflight,
    read_plan_document,
    resolve_plan,
    run_plan,
    write_execution_record,
    write_plan,
)
from contextmap.runtime.reuse import (
    ArtifactStore,
    FileArtifactStore,
    ReuseDecision,
    ReuseKey,
    ReusePolicy,
    StoreLookup,
)

__all__ = [
    "CANONICAL_PROFILE_ID",
    "CONFIG_SCHEMA_VERSION",
    "DEBUG_LEVELS",
    "EFFECTIVE_CONFIG_FILENAME",
    "ArtifactRef",
    "ArtifactStore",
    "BackendConfigurationError",
    "BackendRuntimeMissingError",
    "BackendSpec",
    "BackendUnavailableError",
    "ComponentConfig",
    "ComponentSpec",
    "ComposedRuntime",
    "CompositionError",
    "ConfigProblem",
    "ConfigurationError",
    "ConfigurationSource",
    "EffectiveConfig",
    "ExecutionPlan",
    "ExecutionRecord",
    "FeatureBuildScope",
    "FileArtifactStore",
    "InputsConfig",
    "Interception",
    "PipelineConfig",
    "PipelineError",
    "PipelinePlan",
    "PlanDocumentError",
    "PlannedInput",
    "PlannedStage",
    "PoliciesConfig",
    "PreflightError",
    "PreflightReport",
    "ResolvedSecrets",
    "ResourcesConfig",
    "ReuseDecision",
    "ReuseError",
    "ReuseKey",
    "ReusePolicy",
    "RuntimeConfig",
    "RuntimePreset",
    "RuntimeProvider",
    "StageDeclaration",
    "StageExecutionError",
    "StageExecutor",
    "StageInput",
    "StageRecord",
    "StageRequest",
    "StageUnavailableError",
    "StoreLookup",
    "check_availability",
    "check_component_availability",
    "check_selection",
    "compose",
    "parse_override",
    "predict_reuse",
    "preflight",
    "read_effective_config",
    "read_plan_document",
    "resolve_effective_config",
    "resolve_plan",
    "resolve_secrets",
    "run_plan",
    "write_effective_config",
    "write_execution_record",
    "write_plan",
]
