"""Public contract for the geometric mapping capability.

Geometric Mapping owns persistent 3D geometry in one global map frame: the
authoritative XYZ of every point, a stable reference to it, and the lineage that
says how each coordinate was produced. It stops before semantics: labels,
features, claims, entities and relations are attached by other capabilities
through :class:`GeometryReference`. See
``src/contextmap/geometric_mapping/docs/README.md`` for the full capability
documentation.
"""

from contextmap.geometric_mapping.accumulation import (
    AccumulatedMap,
    AccumulationError,
    MapAccumulator,
    ScanVoxelPolicy,
    accumulate_plan,
    map_provenance_from_plan,
)
from contextmap.geometric_mapping.bulk_geometry import (
    DEFAULT_BLOCK_POINTS,
    GeometryBlock,
    GeometryBlockSource,
)
from contextmap.geometric_mapping.geometry_storage import PackedGeometry, ScanRecord
from contextmap.geometric_mapping.inputs import (
    GeometryInput,
    GeometryInputError,
    GeometryInputPlan,
    GeometryInputRejection,
    InputRejectionReason,
    PointCloudLayout,
    UnsupportedPointCloudLayoutError,
    assemble_geometry_inputs,
    assemble_geometry_inputs_from_artifacts,
    resolve_point_cloud_layout,
)
from contextmap.geometric_mapping.models import (
    Bounds3D,
    GeometricMap,
    GeometricMapProvenance,
    GeometryId,
    GeometryPoint,
    GeometryPointProvenance,
    GeometryReference,
    MapId,
    PointOrigin,
    SpatialIndexMetadata,
    SpatialIndexParameter,
    TransformKind,
    TransformLineage,
    TransformStep,
    geometry_id_for,
    geometry_index_of,
)
from contextmap.geometric_mapping.motion_correction import (
    MotionCorrectionEvidence,
    MotionCorrectionPolicy,
    MotionCorrectionRecord,
    MotionCorrectionState,
    MotionCorrectionVerdict,
    ScanDisposition,
    apply_motion_correction_policy,
    declared_raw_motion_correction,
    unknown_motion_correction,
    verify_motion_correction,
)
from contextmap.geometric_mapping.ports import GeometrySource
from contextmap.geometric_mapping.run_artifact import (
    GeometricMapArtifactManifest,
    GeometricMapArtifactReader,
    GeometricMapArtifactWriter,
    GeometricMapRunId,
    IncompleteMapArtifactError,
    MapArtifactError,
    MapDebugLevel,
    mapping_configuration_fingerprint,
)
from contextmap.geometric_mapping.transformation import (
    GeometryTransformError,
    TracedTransform,
    TransformedScan,
    TransformTrace,
    transform_scan,
    transform_scans,
    transform_trace_residual_m,
    verify_transform_trace,
)

__all__ = [
    "DEFAULT_BLOCK_POINTS",
    "AccumulatedMap",
    "AccumulationError",
    "Bounds3D",
    "GeometricMap",
    "GeometricMapArtifactManifest",
    "GeometricMapArtifactReader",
    "GeometricMapArtifactWriter",
    "GeometricMapProvenance",
    "GeometricMapRunId",
    "GeometryBlock",
    "GeometryBlockSource",
    "GeometryId",
    "GeometryInput",
    "GeometryInputError",
    "GeometryInputPlan",
    "GeometryInputRejection",
    "GeometryPoint",
    "GeometryPointProvenance",
    "GeometryReference",
    "GeometrySource",
    "GeometryTransformError",
    "IncompleteMapArtifactError",
    "InputRejectionReason",
    "MapAccumulator",
    "MapArtifactError",
    "MapDebugLevel",
    "MapId",
    "MotionCorrectionEvidence",
    "MotionCorrectionPolicy",
    "MotionCorrectionRecord",
    "MotionCorrectionState",
    "MotionCorrectionVerdict",
    "PackedGeometry",
    "PointCloudLayout",
    "PointOrigin",
    "ScanDisposition",
    "ScanRecord",
    "ScanVoxelPolicy",
    "SpatialIndexMetadata",
    "SpatialIndexParameter",
    "TracedTransform",
    "TransformKind",
    "TransformLineage",
    "TransformStep",
    "TransformTrace",
    "TransformedScan",
    "UnsupportedPointCloudLayoutError",
    "accumulate_plan",
    "apply_motion_correction_policy",
    "assemble_geometry_inputs",
    "assemble_geometry_inputs_from_artifacts",
    "declared_raw_motion_correction",
    "geometry_id_for",
    "geometry_index_of",
    "map_provenance_from_plan",
    "mapping_configuration_fingerprint",
    "resolve_point_cloud_layout",
    "transform_scan",
    "transform_scans",
    "transform_trace_residual_m",
    "unknown_motion_correction",
    "verify_motion_correction",
    "verify_transform_trace",
]
