"""The versioned vocabulary of spatial relations and the semantics of every predicate.

A relation predicate is not a free-text label: it carries a direction, a symmetry, an inverse and
the frame assumptions that must hold for it to mean anything. This module is the single place
where those facts are stated, so that candidate generation, the geometric evaluators, the decision
policy and the persisted artifact all read the same table.

The vocabulary is small and closed on purpose. It separates four kinds of meaning:

* **proximity** -- how far apart two entities are, with no direction;
* **directional** -- where one entity lies relative to another along a declared axis;
* **topological** -- how the extents of two entities relate as regions;
* **support/contact** -- physical contact, support and lean, which need more than a distance.

Two rules keep the vocabulary honest:

* A predicate is only in the vocabulary when its geometry can be defined and validated. Adding one
  is a new taxonomy version, never a silent extension.
* The converse of a directed predicate is in the vocabulary only when it is a different word for
  the same fact (``ABOVE``/``BELOW``). ``ON_TOP_OF`` and ``LEANING_AGAINST`` have no inverse here:
  ``SUPPORTS`` would be new vocabulary, and no hidden ontology expansion is allowed.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

from contextmap.spatial_relations._checks import require_present

TAXONOMY_VERSION = "spatial-relation-taxonomy-v1"
"""Versioned identity of the vocabulary and of the semantics described in this module."""


class RelationPredicate(Enum):
    """The canonical spatial predicates of Solution 1.

    The subject is the entity the sentence is about and the object is the reference it is related
    to: ``subject PREDICATE object``.
    """

    NEXT_TO = "next_to"
    ABOVE = "above"
    BELOW = "below"
    IN_FRONT_OF = "in_front_of"
    BEHIND = "behind"
    INSIDE = "inside"
    CONTAINS = "contains"
    INTERSECTS = "intersects"
    TOUCHING = "touching"
    ON_TOP_OF = "on_top_of"
    LEANING_AGAINST = "leaning_against"


class PredicateFamily(Enum):
    """The kind of meaning a predicate expresses.

    Attributes:
        PROXIMITY: Distance between two entities, with no direction.
        DIRECTIONAL: Position of one entity relative to another along a declared axis.
        TOPOLOGICAL: How the extents of two entities relate as regions.
        SUPPORT_CONTACT: Contact, support or lean, which need more than a distance.
    """

    PROXIMITY = "proximity"
    DIRECTIONAL = "directional"
    TOPOLOGICAL = "topological"
    SUPPORT_CONTACT = "support_contact"


class FrameRequirement(Enum):
    """What the map frame must declare for a predicate to be evaluable.

    Attributes:
        MAP_FRAME: Only that both entities are expressed in the same map frame.
        UP_AXIS: Also a declared up axis (opposite to gravity) of that frame.
        UP_AND_FORWARD_AXES: Also a declared forward reference axis, which is horizontal.
    """

    MAP_FRAME = "map_frame"
    UP_AXIS = "up_axis"
    UP_AND_FORWARD_AXES = "up_and_forward_axes"


@dataclass(frozen=True, kw_only=True)
class PredicateSpec:
    """The semantics of one predicate.

    Attributes:
        predicate: The predicate described.
        family: The kind of meaning it expresses.
        inverse: The predicate that states the same fact with subject and object swapped. A
            symmetric predicate is its own inverse; ``None`` means the vocabulary has no word for
            the converse.
        frame_requirement: What the map frame must declare for the predicate to be evaluable.
        is_derived: ``True`` when the predicate is never evaluated on its own: its relations are
            generated by inverting the relations of ``inverse``, which is the member of the pair
            that is evaluated directly.
        meaning: The definition, in terms of the geometry the evaluators measure.
    """

    predicate: RelationPredicate
    family: PredicateFamily
    inverse: RelationPredicate | None
    frame_requirement: FrameRequirement
    is_derived: bool
    meaning: str

    def __post_init__(self) -> None:
        """Validate that the description is coherent.

        Raises:
            ValueError: If the meaning is empty, or a derived predicate has no inverse to derive
                from.
        """
        require_present(self, "meaning")
        if self.is_derived and self.inverse is None:
            raise ValueError("a derived predicate needs an inverse to be derived from")

    @property
    def symmetric(self) -> bool:
        """Whether ``a PREDICATE b`` and ``b PREDICATE a`` state the same fact."""
        return self.inverse is self.predicate

    @property
    def directed(self) -> bool:
        """Whether swapping subject and object changes the fact."""
        return not self.symmetric


def _spec(
    predicate: RelationPredicate,
    family: PredicateFamily,
    inverse: RelationPredicate | None,
    frame_requirement: FrameRequirement,
    meaning: str,
    *,
    is_derived: bool = False,
) -> PredicateSpec:
    return PredicateSpec(
        predicate=predicate,
        family=family,
        inverse=inverse,
        frame_requirement=frame_requirement,
        is_derived=is_derived,
        meaning=meaning,
    )


PREDICATE_SPECS: dict[RelationPredicate, PredicateSpec] = {
    spec.predicate: spec
    for spec in (
        _spec(
            RelationPredicate.NEXT_TO,
            PredicateFamily.PROXIMITY,
            RelationPredicate.NEXT_TO,
            FrameRequirement.MAP_FRAME,
            "The bounds of subject and object are separated by a small gap. Symmetric, and "
            "independent of any axis.",
        ),
        _spec(
            RelationPredicate.ABOVE,
            PredicateFamily.DIRECTIONAL,
            RelationPredicate.BELOW,
            FrameRequirement.UP_AXIS,
            "The subject lies above the object along the declared up axis, without sinking into "
            "it, over a footprint that overlaps the object's.",
        ),
        _spec(
            RelationPredicate.BELOW,
            PredicateFamily.DIRECTIONAL,
            RelationPredicate.ABOVE,
            FrameRequirement.UP_AXIS,
            "The subject lies below the object: the inverse of ABOVE, never evaluated on its own.",
            is_derived=True,
        ),
        _spec(
            RelationPredicate.IN_FRONT_OF,
            PredicateFamily.DIRECTIONAL,
            RelationPredicate.BEHIND,
            FrameRequirement.UP_AND_FORWARD_AXES,
            "The subject lies ahead of the object along the declared forward axis, without "
            "sinking into it, over a cross-section that overlaps the object's. The reference is "
            "the map's forward axis, not the orientation of either entity.",
        ),
        _spec(
            RelationPredicate.BEHIND,
            PredicateFamily.DIRECTIONAL,
            RelationPredicate.IN_FRONT_OF,
            FrameRequirement.UP_AND_FORWARD_AXES,
            "The subject lies behind the object: the inverse of IN_FRONT_OF, never evaluated on "
            "its own.",
            is_derived=True,
        ),
        _spec(
            RelationPredicate.INSIDE,
            PredicateFamily.TOPOLOGICAL,
            RelationPredicate.CONTAINS,
            FrameRequirement.MAP_FRAME,
            "The bounds of the subject lie within the bounds of the object.",
        ),
        _spec(
            RelationPredicate.CONTAINS,
            PredicateFamily.TOPOLOGICAL,
            RelationPredicate.INSIDE,
            FrameRequirement.MAP_FRAME,
            "The bounds of the object lie within the bounds of the subject: the inverse of "
            "INSIDE, never evaluated on its own.",
            is_derived=True,
        ),
        _spec(
            RelationPredicate.INTERSECTS,
            PredicateFamily.TOPOLOGICAL,
            RelationPredicate.INTERSECTS,
            FrameRequirement.MAP_FRAME,
            "The bounds of subject and object interpenetrate along every axis. Merely touching "
            "faces do not intersect. Symmetric.",
        ),
        _spec(
            RelationPredicate.TOUCHING,
            PredicateFamily.SUPPORT_CONTACT,
            RelationPredicate.TOUCHING,
            FrameRequirement.MAP_FRAME,
            "Points of subject and object are in contact: the nearest support distance is within "
            "the contact tolerance, over a measurable contact area. Symmetric.",
        ),
        _spec(
            RelationPredicate.ON_TOP_OF,
            PredicateFamily.SUPPORT_CONTACT,
            None,
            FrameRequirement.UP_AXIS,
            "The subject rests on the object: they are in contact, the subject lies above the "
            "object along the declared up axis, and the subject's footprint is supported by the "
            "object's upper surface.",
        ),
        _spec(
            RelationPredicate.LEANING_AGAINST,
            PredicateFamily.SUPPORT_CONTACT,
            None,
            FrameRequirement.UP_AXIS,
            "The subject is in contact with the object while tilted away from the declared up "
            "axis, resting on it sideways: both contact and a compatible relative orientation "
            "are required.",
        ),
    )
}
"""Every predicate's semantics, keyed by predicate."""


def predicate_spec(predicate: RelationPredicate) -> PredicateSpec:
    """Look up the semantics of a predicate.

    Args:
        predicate: A canonical predicate.

    Returns:
        Its direction, symmetry, inverse, frame requirement and meaning.
    """
    return PREDICATE_SPECS[predicate]
