name: Sync labels

on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labels.yml"

permissions:
  issues: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Synchronize repository labels
        uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          prune: false
          token: ${{ secrets.GITHUB_TOKEN }}
