"""Public contracts for backend-agnostic visual perception evidence."""

from .image_preparation import (
    CropOperation,
    ExclusionRegion,
    NormalizeOperation,
    PreparedImage,
    RectifyOperation,
    ResizeOperation,
    SourceImage,
    TransformationRecord,
    ValidRegion,
    prepare_image,
)
from .region_models import (
    ArtifactReference,
    BackendScore,
    BoundingBox,
    CoordinateConvention,
    InlineMask,
    Region2D,
    RegionCandidate,
    RegionIdentity,
    RegionProvenance,
    RejectedRegionCandidate,
    RejectionReason,
)

__all__ = [
    "ArtifactReference",
    "BackendScore",
    "BoundingBox",
    "CoordinateConvention",
    "CropOperation",
    "ExclusionRegion",
    "InlineMask",
    "NormalizeOperation",
    "PreparedImage",
    "RectifyOperation",
    "Region2D",
    "RegionCandidate",
    "RegionIdentity",
    "RegionProvenance",
    "RejectedRegionCandidate",
    "RejectionReason",
    "ResizeOperation",
    "SourceImage",
    "TransformationRecord",
    "ValidRegion",
    "prepare_image",
]
